# Generated by Django 2.2.3 on 2019-07-07 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('ACTUAL', 'Actual')], max_length=9),
        ),
    ]
