# Generated by Django 2.2.3 on 2019-07-07 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_app', '0002_person_children'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='children',
        ),
    ]
